### PR TITLE
fix: prevent Finch connection pool exhaustion on LLM stream cancellation

### LINKED ISSUE #428: Finch connection pool exhaustion causes LLM stream failures in prod
## Summary

LLM streaming requests are failing in production with `RuntimeError` due to Finch connection pool exhaustion. The downstream HTTP client cannot acquire a connection within the configured timeout, causing agent LLM calls to crash.

**Sentry Issue**: [ELIXIR-2C](https://frontman-gm.sentry.io/issues/ELIXIR-2C)
**First Seen**: 2026-02-24 08:15 UTC
**Last Seen**: 2026-02-24 08:50 UTC
**Occurrences**: 6
**Environment**: prod

## Error

```
RuntimeError: LLM stream error: {:error, %RuntimeError{message: "Finch was unable to provide a connection within the timeout due to excess queuing for connections. Consider adjusting the pool size, count, timeout or reducing the rate of requests if it is possible that the downstream service is unable to keep up with the current rate."}}
```

## Stacktrace

```
at :telemetry.span/3 (telemetry.erl:324)
at SwarmAi.execute_llm_call/4 (lib/swarm_ai.ex:474)
at SwarmAi.LLM.Response.from_stream/1 (lib/swarm_ai/llm/response.ex:57)
at Enum.reduce/3 (lib/enum.ex:4570)
at SwarmAi.LLM.FrontmanServer.Agents.LLMClient.to_swarm_chunk/2 (lib/frontman_server/agents/llm_client.ex:235)
```

## Likely Cause

The Finch connection pool (used for outbound HTTP to LLM providers) is undersized for the current request volume. Under load, requests queue up waiting for an available connection and eventually time out.

## Suggested Investigation

- Review the Finch pool configuration (`pool_size`, `count`, `pool_timeout`) for the LLM client
- Check if there's a connection leak (streams not being properly closed on error/cancel)
- Consider whether concurrent LLM calls need to be bounded upstream (e.g., a semaphore or rate limiter)
- Check if the LLM provider was experiencing latency at the time, causing connections to be held longer than usual

## Runtime

- **Elixir**: 1.19.3 (Erlang/OTP 28)
- **Server**: ubuntu-8gb-nbg1-1
- **Release**: frontman_server@0.0.1

### PR DESCRIPTION
**Pull request by BlueHotDog**
## Summary

Fixes #428 — Sentry error `ELIXIR-2C` (`RuntimeError: LLM stream error`) caused by Finch pool exhaustion under concurrent LLM streaming.

- **Increase Finch pool capacity** from 8 → 32 connections (`config.exs`)
- **Add `StreamCleanup` module** using linked cleanup process pattern to guarantee `cancel_fn` is always called — on normal consumption, `Enum.take` halt, raise, and process death (`Process.exit`)
- **Wrap both LLM stream call sites** (`LLMClient.stream/3` and `TitleGenerator.call_llm/4`)

## Root Cause

`ReqLLM.stream_text/3` returns a `cancel` function that releases the Finch HTTP connection. When `Runtime.cancel/2` kills the consuming process via `Process.exit(pid, :cancelled)`, the cancel function is never called — `try/after` and `Stream.resource` cleanup do **not** fire on the target of `Process.exit`. The connection leaks back to the pool only after provider-side timeout (up to 150s), exhausting the default 8-connection pool under concurrent load.

## Design

`StreamCleanup.wrap_stream/2` uses two complementary mechanisms:

1. **`Stream.transform` after callback** — fires on normal completion, `Enum.take` halt, and raise. Calls `cancel_fn` directly (idempotent) and signals the cleanup process to stand down.

2. **Linked cleanup process** — traps exits from the caller. If the caller dies before the after callback fires, the cleanup process calls `cancel_fn` as a safety net. Even `:kill` signals propagate as `:killed` to linked processes, which can be trapped.

## Test Coverage

10 integration tests covering:
- Full consumption → cancel called
- Process killed (`:cancelled`) → cancel called via cleanup process
- Stream raises → cancel called via after_fn
- Partial consumption (`Enum.take`) → cancel called
- `:kill` signal → cancel called (`:killed` is trappable by linked process)
- Empty streams → cancel called
- Stream laziness preserved
- Cancel errors handled gracefully (no crash)
- Cleanup process lifetime (no leaks)
- Sequential `wrap_stream` calls in same process

## Files Changed

| File | Change |
|---|---|
| `config/config.exs` | Finch pool: 8 → 32 connections |
| `tasks/stream_cleanup.ex` | **New** — linked cleanup process module |
| `tasks/execution/llm_client.ex` | Wrap stream with `StreamCleanup` |
| `tasks/title_generator.ex` | Wrap stream with `StreamCleanup` |
| `tasks/interaction.ex` | Formatter-only (auto-applied by `mix format`) |
| `tasks/stream_cleanup_test.exs` | **New** — 10 integration tests |

---

<a href="https://app.devin.ai/review/frontman-ai/frontman/pull/483" target="_blank">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://static.devin.ai/assets/gh-open-in-devin-review-dark.svg?v=1">
    Open with Devin
  </picture>
</a>

### CODE REVIEW

File: apps/frontman_server/test/frontman_server/tasks/stream_cleanup_test.exs [hunk 1]
```diff
@@ -0,0 +1,212 @@
+defmodule FrontmanServer.Tasks.StreamCleanupTest do
```
Comment (BlueHotDog) [inline apps/frontman_server/test/frontman_server/tasks/stream_cleanup_test.exs:1]: these are nice unit tests, but i'm missing integration tests

File: apps/frontman_server/lib/frontman_server/tasks/stream_cleanup.ex [hunk 2]
```diff
@@ -0,0 +1,117 @@
...
+    receive do
+      {:cleanup_ready, ^pid} -> pid
+    end
+  end
+
+  defp do_cancel(cancel_fn) do
+    cancel_fn.()
+  rescue
+    e ->
+      Logger.debug("StreamCleanup: cancel raised #{Exception.message(e)}")
```
Comment (BlueHotDog) [inline apps/frontman_server/lib/frontman_server/tasks/stream_cleanup.ex]: why is this debug? how will we monitor this?
